"""empty message

Revision ID: 19ff4b35028d
Revises: 2441887bf8c4
Create Date: 2020-12-04 15:28:03.702688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ff4b35028d'
down_revision = '2441887bf8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'space_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'space_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
