"""empty message

Revision ID: 2441887bf8c4
Revises: b5142dba8bc5
Create Date: 2020-12-04 15:23:29.018486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2441887bf8c4'
down_revision = 'b5142dba8bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'space_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'space_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
