"""empty message

Revision ID: b6acda51f7ba
Revises: ad1a9936763b
Create Date: 2020-12-10 15:31:01.977975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6acda51f7ba'
down_revision = 'ad1a9936763b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservation_space_id_fkey', 'reservation', type_='foreignkey')
    op.drop_constraint('reservation_user_id_fkey', 'reservation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reservation_user_id_fkey', 'reservation', 'user', ['user_id'], ['id'])
    op.create_foreign_key('reservation_space_id_fkey', 'reservation', 'space', ['space_id'], ['id'])
    # ### end Alembic commands ###
